import { Feather, FontAwesome5 } from "@expo/vector-icons"

// Enhanced Quick Actions with premium styling
export const QUICK_ACTIONS = [
  {
    id: "nearby-rides",
    icon: "map-marker-alt",
    iconLibrary: FontAwesome5,
    title: "Nearby Rides",
    description: "Find autos nearby",
    gradient: ["#667eea", "#764ba2"],
    iconColor: "#ffffff",
    route: "NearbyRides",
    analytics: "quick_action_nearby_rides",
    badge: "12 available",
  },
  {
    id: "schedule",
    icon: "clock",
    iconLibrary: Feather,
    title: "Schedule Ride",
    description: "Plan your journey",
    gradient: ["#f093fb", "#f5576c"],
    iconColor: "#ffffff",
    route: "Schedule",
    analytics: "quick_action_schedule",
    badge: "Book ahead",
  },
  {
    id: "favorites",
    icon: "heart",
    iconLibrary: Feather,
    title: "Saved Places",
    description: "Quick destinations",
    gradient: ["#4facfe", "#00f2fe"],
    iconColor: "#ffffff",
    route: "Favorites",
    analytics: "quick_action_favorites",
    badge: "5 saved",
  },
  {
    id: "support",
    icon: "headphones",
    iconLibrary: Feather,
    title: "24/7 Support",
    description: "We're here to help",
    gradient: ["#43e97b", "#38f9d7"],
    iconColor: "#ffffff",
    route: "Support",
    analytics: "quick_action_support",
    badge: "Live chat",
  },
]

// Premium offers with enhanced design
export const PREMIUM_OFFERS = [
  {
    id: "welcome-offer",
    icon: "gift",
    iconLibrary: Feather,
    badgeText: "LIMITED TIME",
    title: "50% OFF First Ride",
    subtitle: "Welcome bonus for new users",
    details: "Use code WELCOME50",
    originalPrice: "₹200",
    discountedPrice: "₹100",
    gradient: ["#667eea", "#764ba2"],
    validUntil: "2024-12-31",
    analytics: "premium_offer_welcome",
    popularity: "Most Popular",
  },
  {
    id: "vip-booking",
    icon: "crown",
    iconLibrary: FontAwesome5,
    badgeText: "VIP EXCLUSIVE",
    title: "Priority Booking",
    subtitle: "Skip the waiting queue",
    details: "Instant ride confirmation",
    gradient: ["#f093fb", "#f5576c"],
    analytics: "premium_offer_vip",
    popularity: "Premium",
  },
  {
    id: "cashback",
    icon: "dollar-sign",
    iconLibrary: Feather,
    badgeText: "WEEKEND SPECIAL",
    title: "20% Cashback",
    subtitle: "On all weekend rides",
    details: "Valid Sat-Sun only",
    gradient: ["#43e97b", "#38f9d7"],
    analytics: "premium_offer_cashback",
    popularity: "Trending",
  },
  {
    id: "referral",
    icon: "users",
    iconLibrary: Feather,
    badgeText: "REFER & EARN",
    title: "Invite Friends",
    subtitle: "Earn ₹100 per referral",
    details: "Both get rewards",
    gradient: ["#4facfe", "#00f2fe"],
    analytics: "premium_offer_referral",
    popularity: "Hot Deal",
  },
]
